import { RadarConfig, CalculatedRadarPerformance } from '../radar/types.ts';
import {
  LuaGenerationOptions,
  GeneratedLuaScript,
  LuaSection,
  LuaCommand,
} from './types.ts';
import {
  buildChannelSection,
  buildProfileSection,
  buildChirpSection,
  buildFrameSection,
  buildDca1000Section,
  buildAutomationSection,
} from './studio2.ts';
import { getDeviceById } from '../radar/devices/awr1843.ts';

function formatCommandLine(cmd: LuaCommand): string {
  const argsStr = cmd.args.join(', ');
  const call = `${cmd.apiName}(${argsStr})`;
  if (cmd.comment) {
    return `${call.padEnd(50, ' ')} -- ${cmd.comment}`;
  }
  return call;
}

export function generateStudio2Lua(
  config: RadarConfig,
  perf: CalculatedRadarPerformance,
  options: LuaGenerationOptions
): GeneratedLuaScript {
  const device = getDeviceById(config.device);
  const lines: string[] = [];

  // File Header
  lines.push('-- ==============================================================================');
  lines.push('-- Generated by mmWave Studio Parameter Lab');
  lines.push(`-- Target Device: ${device.name}`);
  lines.push('-- Studio Backend: TI mmWave Studio 2.x (ar1.* API)');
  lines.push(`-- Mode: ${options.mode.toUpperCase()}`);
  lines.push(`-- Generated At: ${new Date().toISOString()}`);
  if (options.metadata?.experimentName) {
    lines.push(`-- Experiment: ${options.metadata.experimentName}`);
  }
  if (options.metadata?.author) {
    lines.push(`-- Author: ${options.metadata.author}`);
  }
  if (options.metadata?.notes) {
    lines.push(`-- Notes: ${options.metadata.notes.replace(/\n/g, ' ')}`);
  }
  lines.push('-- ==============================================================================');
  lines.push('');

  // Performance Summary Header
  if (options.includeCalculatedHeader) {
    lines.push('-- ------------------------------------------------------------------------------');
    lines.push('-- PREDICTED PHYSICAL PERFORMANCE:');
    lines.push(`--   * Effective ADC Bandwidth:   ${perf.effectiveAdcBandwidthMHz.toFixed(2)} MHz`);
    lines.push(`--   * Range Resolution:          ${perf.rangeResolutionCm.toFixed(2)} cm (${perf.rangeResolutionM.toFixed(4)} m)`);
    lines.push(`--   * Theoretical Max Range:     ${perf.theoreticalMaxRangeM.toFixed(2)} m (Rec. with 0.9 margin: ${perf.recommendedMaxRangeM.toFixed(2)} m)`);
    lines.push(`--   * Chirp Cycle Time:          ${perf.chirpCycleTimeUs.toFixed(2)} us (Chirp Rate: ${perf.chirpRepetitionFrequencyHz.toFixed(0)} Hz)`);
    lines.push(`--   * Max Unambiguous Velocity:  ${perf.maxUnambiguousVelocityMps.toFixed(2)} m/s (${perf.maxUnambiguousVelocityKmh.toFixed(2)} km/h)`);
    lines.push(`--   * Velocity Resolution:       ${perf.velocityResolutionMps.toFixed(4)} m/s (${perf.velocityResolutionKmh.toFixed(2)} km/h)`);
    lines.push(`--   * Frame Chirps:              ${perf.chirpsPerFrame} (${perf.chirpsPerLoop} chirps/loop x ${config.frame.loops} loops)`);
    lines.push(`--   * Frame Active Time:         ${perf.frameActiveTimeMs.toFixed(2)} ms / Period: ${config.frame.periodicityMs} ms (Duty: ${perf.dutyCyclePercent.toFixed(1)}%)`);
    lines.push(`--   * Virtual Antennas:          ${perf.virtualAntennaCountAzimuth} Azimuth + ${perf.virtualAntennaCountElevation} Elevation (Total: ${perf.virtualAntennaCountTotal})`);
    lines.push(`--   * Est. Raw ADC Data Size:    ${perf.dataSizePerFrameMB.toFixed(2)} MB/frame | Total: ${perf.totalDataSizeMB.toFixed(2)} MB (${config.frame.frames === 0 ? 'Continuous' : `${config.frame.frames} frames`})`);
    lines.push('-- ------------------------------------------------------------------------------');
    lines.push('');
  }

  const sections: LuaSection[] = [];

  if (options.mode === 'full_automation') {
    sections.push(buildAutomationSection());
  }

  // Core verified radar config
  sections.push(buildChannelSection(config));
  sections.push(buildProfileSection(config));
  sections.push(buildChirpSection(config));
  sections.push(buildFrameSection(config));

  if (options.mode === 'config_and_capture' || options.mode === 'full_automation') {
    sections.push(buildDca1000Section(options.captureFilePath));
  }

  sections.forEach((sec) => {
    lines.push(`-- ------------------------------------------------------------------------------`);
    lines.push(`-- ${sec.title}`);
    if (sec.description) {
      lines.push(`-- ${sec.description}`);
    }
    if (!sec.isVerified) {
      lines.push('-- [STATUS: NOT VERIFIED / TEMPLATE - Check environment parameters]');
    } else {
      lines.push('-- [STATUS: VERIFIED TI mmWave Studio 2.x API]');
    }
    lines.push(`-- ------------------------------------------------------------------------------`);

    sec.commands.forEach((cmd) => {
      lines.push(formatCommandLine(cmd));
    });
    lines.push('');
  });

  lines.push('-- End of generated script');

  return {
    code: lines.join('\n'),
    mode: options.mode,
    backendName: 'mmWave Studio 2.x (ar1.*)',
    verifiedStatus: {
      radarConfigVerified: true,
      dca1000Verified: options.mode !== 'config_only',
      automationVerified: options.mode === 'full_automation',
    },
  };
}
