import { PresetScenario } from './types.ts';

export const PRESETS: PresetScenario[] = [
  {
    id: 'basic-range',
    name: 'Basic Range Experiment',
    category: 'ranging',
    tag: 'High Resolution Ranging',
    description: 'High frequency slope (45 MHz/µs) designed for fine distance discrimination and range profile verification.',
    designIntent: 'Maximizes effective swept bandwidth (Badc ≈ 2.3 GHz) to achieve ~6.5 cm range resolution.',
    recommendedUse: 'Indoor static target ranging, liquid level sensing, distance calibration against corner reflectors.',
    config: {
      device: 'awr1843boost',
      profile: {
        profileId: 0,
        startFrequencyGHz: 77.0,
        idleTimeUs: 50.0,
        adcStartTimeUs: 6.0,
        rampEndTimeUs: 60.0,
        frequencySlopeMHzUs: 45.0,
        adcSamples: 256,
        sampleRateKsps: 5000,
        rxGainDb: 30,
        hpfCornerFreq1Khz: 175,
        hpfCornerFreq2Khz: 350,
      },
      channels: {
        rxEnabled: [true, true, true, true],
        txEnabled: [true, false, false],
      },
      chirps: [
        { chirpIndex: 0, profileId: 0, txEnabled: [true, false, false] },
      ],
      frame: {
        chirpStartIndex: 0,
        chirpEndIndex: 0,
        loops: 64,
        frames: 100,
        periodicityMs: 50.0,
        triggerDelayMs: 0.0,
      },
      adc: {
        complex: true,
        bitsPerComponent: 16,
        iqSwap: false,
      },
    },
  },
  {
    id: 'basic-doppler',
    name: 'Basic Doppler Experiment',
    category: 'doppler',
    tag: 'High Velocity Sensing',
    description: 'Ultra-fast chirp cycle (40 µs) with single TX antenna to achieve high maximum unambiguous velocity (> 24 m/s / ~87 km/h).',
    designIntent: 'Minimizes chirp cycle time (Tchirp = 40 µs) to prevent velocity aliasing on fast-moving targets.',
    recommendedUse: 'Automotive speed measurement, drone tracking, moving vehicles, sports velocity analysis.',
    config: {
      device: 'awr1843boost',
      profile: {
        profileId: 0,
        startFrequencyGHz: 77.0,
        idleTimeUs: 8.0,
        adcStartTimeUs: 4.0,
        rampEndTimeUs: 32.0,
        frequencySlopeMHzUs: 15.0,
        adcSamples: 128,
        sampleRateKsps: 5000,
        rxGainDb: 30,
        hpfCornerFreq1Khz: 175,
        hpfCornerFreq2Khz: 350,
      },
      channels: {
        rxEnabled: [true, true, true, true],
        txEnabled: [true, false, false],
      },
      chirps: [
        { chirpIndex: 0, profileId: 0, txEnabled: [true, false, false] },
      ],
      frame: {
        chirpStartIndex: 0,
        chirpEndIndex: 0,
        loops: 128,
        frames: 100,
        periodicityMs: 40.0,
        triggerDelayMs: 0.0,
      },
      adc: {
        complex: true,
        bitsPerComponent: 16,
        iqSwap: false,
      },
    },
  },
  {
    id: 'basic-aoa',
    name: 'Basic AoA Experiment (3D TDM-MIMO)',
    category: 'mimo',
    tag: 'Full 3D MIMO Array',
    description: 'Standard 3-Chirp TDM-MIMO sequence activating TX1 (azimuth), TX2 (elevation), and TX3 (azimuth) with 4 RX antennas.',
    designIntent: 'Synthesizes 12 virtual antennas (8 azimuth elements for ~14.3° AoA resolution + 4 elevation elements).',
    recommendedUse: 'Point cloud generation, angle-of-arrival testing, 3D object localization, radar SLAM experiments.',
    config: {
      device: 'awr1843boost',
      profile: {
        profileId: 0,
        startFrequencyGHz: 77.0,
        idleTimeUs: 30.0,
        adcStartTimeUs: 6.0,
        rampEndTimeUs: 50.0,
        frequencySlopeMHzUs: 25.0,
        adcSamples: 256,
        sampleRateKsps: 6250,
        rxGainDb: 30,
        hpfCornerFreq1Khz: 175,
        hpfCornerFreq2Khz: 350,
      },
      channels: {
        rxEnabled: [true, true, true, true],
        txEnabled: [true, true, true],
      },
      chirps: [
        { chirpIndex: 0, profileId: 0, txEnabled: [true, false, false] },
        { chirpIndex: 1, profileId: 0, txEnabled: [false, true, false] },
        { chirpIndex: 2, profileId: 0, txEnabled: [false, false, true] },
      ],
      frame: {
        chirpStartIndex: 0,
        chirpEndIndex: 2,
        loops: 64,
        frames: 100,
        periodicityMs: 50.0,
        triggerDelayMs: 0.0,
      },
      adc: {
        complex: true,
        bitsPerComponent: 16,
        iqSwap: false,
      },
    },
  },
  {
    id: 'micro-motion',
    name: 'Micro-motion Experiment',
    category: 'vibration',
    tag: 'Fine Velocity & Vibration',
    description: 'Extended Doppler observation window with 256 loops for ultra-fine velocity resolution and micro-Doppler spectrograms.',
    designIntent: 'High Doppler observation time (Tobs > 20 ms) allows resolving millimeter-per-second velocity changes.',
    recommendedUse: 'Vital signs (respiration and heartbeat monitoring), micro-Doppler human gesture recognition, industrial machinery vibration.',
    config: {
      device: 'awr1843boost',
      profile: {
        profileId: 0,
        startFrequencyGHz: 77.0,
        idleTimeUs: 30.0,
        adcStartTimeUs: 6.0,
        rampEndTimeUs: 50.0,
        frequencySlopeMHzUs: 30.0,
        adcSamples: 256,
        sampleRateKsps: 6250,
        rxGainDb: 36,
        hpfCornerFreq1Khz: 175,
        hpfCornerFreq2Khz: 350,
      },
      channels: {
        rxEnabled: [true, true, true, true],
        txEnabled: [true, false, false],
      },
      chirps: [
        { chirpIndex: 0, profileId: 0, txEnabled: [true, false, false] },
      ],
      frame: {
        chirpStartIndex: 0,
        chirpEndIndex: 0,
        loops: 256,
        frames: 100,
        periodicityMs: 50.0,
        triggerDelayMs: 0.0,
      },
      adc: {
        complex: true,
        bitsPerComponent: 16,
        iqSwap: false,
      },
    },
  },
  {
    id: 'custom-template',
    name: 'Custom Experiment Template',
    category: 'custom',
    tag: 'General Starting Point',
    description: 'Clean balanced baseline configuration ready for user customization across all profile and frame fields.',
    designIntent: 'Conservative timing and sample rates ensuring safe duty cycle and ample ADC margin.',
    recommendedUse: 'Custom experiment design, laboratory prototyping, educational demos.',
    config: {
      device: 'awr1843boost',
      profile: {
        profileId: 0,
        startFrequencyGHz: 77.0,
        idleTimeUs: 50.0,
        adcStartTimeUs: 6.0,
        rampEndTimeUs: 60.0,
        frequencySlopeMHzUs: 30.0,
        adcSamples: 256,
        sampleRateKsps: 5000,
        rxGainDb: 30,
        hpfCornerFreq1Khz: 175,
        hpfCornerFreq2Khz: 350,
      },
      channels: {
        rxEnabled: [true, true, true, true],
        txEnabled: [true, true, true],
      },
      chirps: [
        { chirpIndex: 0, profileId: 0, txEnabled: [true, false, false] },
        { chirpIndex: 1, profileId: 0, txEnabled: [false, true, false] },
        { chirpIndex: 2, profileId: 0, txEnabled: [false, false, true] },
      ],
      frame: {
        chirpStartIndex: 0,
        chirpEndIndex: 2,
        loops: 64,
        frames: 100,
        periodicityMs: 50.0,
        triggerDelayMs: 0.0,
      },
      adc: {
        complex: true,
        bitsPerComponent: 16,
        iqSwap: false,
      },
    },
  },
];

export function getPresetById(id: string): PresetScenario {
  return PRESETS.find((p) => p.id === id) || PRESETS[0];
}
