import React, { useState } from 'react';
import { HelpCircle, X } from 'lucide-react';
import { useLanguage } from '../../i18n/context.tsx';

export interface ParameterHelpData {
  title: string;
  unit: string;
  physicalMeaning: string;
  ifIncreased: string;
  ifDecreased: string;
  relatedOutputs: string[];
}

export const PARAMETER_HELP_EN: Record<string, ParameterHelpData> = {
  startFrequencyGHz: {
    title: 'Start Frequency (f0)',
    unit: 'GHz',
    physicalMeaning: 'The initial carrier frequency at the beginning of the FMCW chirp ramp.',
    ifIncreased: 'Carrier wavelength lambda shrinks; phase sensitivity increases; operates at a higher millimeter-wave band.',
    ifDecreased: 'Wavelength lambda increases; absolute frequency moves towards the 76 GHz lower edge.',
    relatedOutputs: ['Carrier Wavelength (λ)', 'Doppler Velocity Scale', 'Array Spacing in λ'],
  },
  frequencySlopeMHzUs: {
    title: 'Frequency Slope (S)',
    unit: 'MHz/µs',
    physicalMeaning: 'Rate of linear chirp frequency increase over time (df/dt) generated by the fractional-N PLL synthesizer.',
    ifIncreased: 'Swept bandwidth expands faster, improving range resolution (smaller ΔR), but beat frequency increases, reducing maximum detection range.',
    ifDecreased: 'Swept bandwidth decreases, worsening range resolution, but allowing greater maximum range for a given ADC sampling rate.',
    relatedOutputs: ['Effective Bandwidth (Badc)', 'Range Resolution (ΔR)', 'Maximum Unambiguous Range (Rmax)'],
  },
  idleTimeUs: {
    title: 'Idle Time (Tidle)',
    unit: 'µs',
    physicalMeaning: 'Time between end of previous chirp and start of next chirp, allowing PLL synthesizer VCO frequency settling and charge pump reset.',
    ifIncreased: 'Improves PLL spectral purity and phase settle margin, but extends chirp cycle time, lowering maximum unambiguous velocity and decreasing duty cycle efficiency.',
    ifDecreased: 'Shortens chirp cycle, increasing maximum unambiguous velocity, but too low (< 2-5 µs) causes VCO phase unlock/distortion.',
    relatedOutputs: ['Chirp Cycle Time (Tchirp)', 'Max Velocity (Vmax)', 'Frame Active Time'],
  },
  adcStartTimeUs: {
    title: 'ADC Start Time (Tadc_start)',
    unit: 'µs',
    physicalMeaning: 'Delay from chirp ramp start until ADC begins sampling. Prevents sampling during initial RF synthesizer transient overshoot and IF filter settling.',
    ifIncreased: 'Ensures analog HPF and IF filters are fully settled, avoiding DC transients, but leaves less remaining ramp time for ADC sampling.',
    ifDecreased: 'Allows more time for ADC sampling, but risking transient filter settle ringing in early ADC samples.',
    relatedOutputs: ['ADC Sampling Window Margin', 'Ramp End Settle Time'],
  },
  rampEndTimeUs: {
    title: 'Ramp End Time (Tramp)',
    unit: 'µs',
    physicalMeaning: 'Total duration of the linear frequency ramp transmission. Must accommodate ADC Start Time + ADC Sampling Time.',
    ifIncreased: 'Allows longer ADC sampling windows or more ADC samples, but extends chirp cycle time.',
    ifDecreased: 'Shortens chirp cycle, increasing max velocity, but must be >= ADC Start Time + ADC Sampling Time to avoid truncation.',
    relatedOutputs: ['Full Sweep Bandwidth', 'Chirp Cycle Time', 'ADC Window Slack Margin'],
  },
  adcSamples: {
    title: 'ADC Samples (Nadc)',
    unit: 'samples',
    physicalMeaning: 'Number of raw digital time-domain samples collected per chirp per RX antenna by the high-speed ADC.',
    ifIncreased: 'Expands ADC sampling duration Tadc and effective bandwidth, improving range resolution and processing gain, but increases raw data size.',
    ifDecreased: 'Reduces sampling duration and data payload, but narrows effective bandwidth and worsens range resolution.',
    relatedOutputs: ['ADC Sampling Time (Tadc)', 'Effective Bandwidth (Badc)', 'Range Resolution (ΔR)', 'Data Payload Size'],
  },
  sampleRateKsps: {
    title: 'ADC Sample Rate (Fs)',
    unit: 'ksps (kilo-samples/s)',
    physicalMeaning: 'Sampling frequency of the ADC converter. Dictates maximum IF beat frequency supported before aliasing occurs.',
    ifIncreased: 'Expands maximum unambiguous range (Rmax = Fs*c / (2*S)), but shortens ADC duration Tadc for a fixed sample count.',
    ifDecreased: 'Lengthens ADC duration Tadc, but reduces maximum range.',
    relatedOutputs: ['Maximum Unambiguous Range (Rmax)', 'ADC Sampling Time', 'IF Bandwidth Limit'],
  },
  rxGainDb: {
    title: 'RX Gain',
    unit: 'dB',
    physicalMeaning: 'Total analog baseband programmable gain amplifier (PGA) amplification applied to received IF echo signals before ADC digitization.',
    ifIncreased: 'Increases sensitivity for detecting small/distant radar cross-section (RCS) targets, but risks ADC saturation on strong nearby reflectors.',
    ifDecreased: 'Prevents ADC clipping from large stationary clutter or direct TX-RX leakage, at the cost of sensitivity for weak targets.',
    relatedOutputs: ['ADC Dynamic Range', 'Receiver Sensitivity'],
  },
  loops: {
    title: 'Chirp Loops (Nd)',
    unit: 'loops/frame',
    physicalMeaning: 'Number of times the chirp sequence (e.g. TDM sequence) is repeated inside a single frame. Formulates the Doppler FFT dimension.',
    ifIncreased: 'Extends Doppler observation time Tobs = Nd*Ttx, refining velocity resolution (smaller Δv) and boosting SNR gain, but multiplies frame size and active time.',
    ifDecreased: 'Reduces frame active time and data payload, but broadens Doppler velocity bins, worsening velocity resolution.',
    relatedOutputs: ['Doppler Velocity Resolution (Δv)', 'Doppler Observation Window (Tobs)', 'Frame Active Time', 'Data Size'],
  },
  periodicityMs: {
    title: 'Frame Periodicity',
    unit: 'ms',
    physicalMeaning: 'Total time interval between the start of successive frames. Determines frame rate (FPS = 1000 / Periodicity).',
    ifIncreased: 'Lowers frame rate and duty cycle, allowing device cooldown and reducing average Ethernet data transfer rate.',
    ifDecreased: 'Increases frame rate for responsive real-time tracking, but must remain strictly greater than Frame Active Time (duty cycle <= 100%).',
    relatedOutputs: ['Frame Rate (FPS)', 'Duty Cycle (%)', 'Average Streaming Data Rate (MB/s)'],
  },
  frames: {
    title: 'Number of Frames',
    unit: 'frames',
    physicalMeaning: 'Total number of radar frames to capture. Setting to 0 in mmWave Studio configures continuous infinite capture until stopped.',
    ifIncreased: 'Extends experimental recording duration and increases total saved raw binary file size.',
    ifDecreased: 'Captures fewer frames for rapid snapshot testing.',
    relatedOutputs: ['Total Session Data Size (MB/GB)', 'Capture Duration'],
  },
};

export const PARAMETER_HELP_ZH: Record<string, ParameterHelpData> = {
  startFrequencyGHz: {
    title: '起始频率 (Start Frequency, f0)',
    unit: 'GHz',
    physicalMeaning: 'FMCW 调频连续波 Chirp 斜坡发射开始时的初始载波频率。',
    ifIncreased: '载波波长 λ 缩短，相位灵敏度提高，雷达工作在更高频段。',
    ifDecreased: '波长 λ 增加，绝对工作频率向 76 GHz 下边沿移动。',
    relatedOutputs: ['载波波长 (λ)', '多普勒速度尺度', '天线物理间距与电尺寸'],
  },
  frequencySlopeMHzUs: {
    title: '调频斜率 (Frequency Slope, S)',
    unit: 'MHz/µs',
    physicalMeaning: '雷达锁相环 (PLL) 发生器使射频频率随时间线性增加的速率 (df/dt)。',
    ifIncreased: '有效扫频带宽扩展更快，距离分辨率显著提升（ΔR 变小，测距更精细），但相同距离下的中频拍频增加，导致最大无模糊探测距离收缩。',
    ifDecreased: '扫频带宽变窄，距离分辨率变粗，但在相同 ADC 采样率下允许探测更远的目标距离。',
    relatedOutputs: ['有效采样带宽 (Badc)', '距离分辨率 (ΔR)', '最大不模糊探测距离 (Rmax)'],
  },
  idleTimeUs: {
    title: '空闲时间 (Idle Time, Tidle)',
    unit: 'µs',
    physicalMeaning: '前一个 Chirp 结束至下一个 Chirp 开始之间的等待时间，供锁相环 VCO 压控振荡器频率重置与建立锁定。',
    ifIncreased: '提高 PLL 频谱纯度与相位建立裕量，但拉长单 Chirp 周期，导致多普勒最大不模糊速度降低并降低占空比利用率。',
    ifDecreased: '缩短单 Chirp 周期，提升最大不模糊速度，但过低（< 2 µs）会导致锁相环失锁或相位非线性失真。',
    relatedOutputs: ['单 Chirp 周期时间 (Tchirp)', '最大不模糊速度 (Vmax)', '帧有效发射时间'],
  },
  adcStartTimeUs: {
    title: 'ADC 启动时间 (ADC Start Time)',
    unit: 'µs',
    physicalMeaning: '从 Chirp 斜坡开始发射到 ADC 开始采集数字采样点之间的延迟。避开射频过冲与中频高通滤波器初始瞬态。',
    ifIncreased: '确保模拟高通滤波器 (HPF) 与中频链路完全建立稳定，消除 DC 瞬态冲击，但会缩短后续可用的采样时间。',
    ifDecreased: '为 ADC 采样留出更多时隙，但过短会在前段采样点中引入滤波器过渡瞬态波动。',
    relatedOutputs: ['ADC 采样窗口容差裕量', 'Ramp 结束时延'],
  },
  rampEndTimeUs: {
    title: 'Ramp 结束时间 (Ramp End Time)',
    unit: 'µs',
    physicalMeaning: '单次线性调频斜坡发射的总持续时间。必须大于等于 ADC 启动时间 + ADC 采样持续时间。',
    ifIncreased: '允许采集更多 ADC 采样点或使用更长采样窗口，但会增加单 Chirp 周期。',
    ifDecreased: '缩短 Chirp 周期以提高速度测量上限，但必须确保采样窗口不被强制截断。',
    relatedOutputs: ['全斜坡扫频总带宽', '单 Chirp 周期', '采样窗口剩余裕量 (Slack)'],
  },
  adcSamples: {
    title: 'ADC 采样点数 (ADC Samples, Nadc)',
    unit: '点 (samples)',
    physicalMeaning: '每个 Chirp 内每路 RX 接收通道由高速 ADC 采集的原始时域采样点数。',
    ifIncreased: '延长 ADC 采样时间 Tadc，增加有效带宽 Badc，改善距离分辨率并提高处理增益，但增加数据量。',
    ifDecreased: '缩减采样窗口与数据存储体积，但有效带宽减小，导致测距分辨率粗化。',
    relatedOutputs: ['ADC 采样时间 (Tadc)', '有效采样带宽 (Badc)', '距离分辨率 (ΔR)', '原始数据大小'],
  },
  sampleRateKsps: {
    title: 'ADC 采样率 (ADC Sample Rate, Fs)',
    unit: 'ksps (千点/秒)',
    physicalMeaning: 'ADC 模数转换器的采样频率。决定雷达中频 (IF) 能够无混叠采样的最大差频拍频。',
    ifIncreased: '提高最大不模糊测距上限 (Rmax)，但在点数固定时会缩短采样持续时间 Tadc。',
    ifDecreased: '延长采样时间 Tadc，但缩小可探测的最大物理距离。',
    relatedOutputs: ['最大不模糊探测距离 (Rmax)', '采样时间 (Tadc)', '中频 IF 带宽限制'],
  },
  rxGainDb: {
    title: '接收模拟增益 (RX Gain)',
    unit: 'dB',
    physicalMeaning: '中频基带可编程增益放大器 (PGA) 在 ADC 数字化之前对微弱雷达回波施加的模拟放大倍数。',
    ifIncreased: '提高对弱小雷达散射截面 (RCS) 或远距离目标的检测灵敏度，但在面对近距离强反射体时可能导致 ADC 饱和削顶。',
    ifDecreased: '防止直达波泄露或强静止杂波导致 ADC 削顶溢出，但会降低弱目标的检测距离。',
    relatedOutputs: ['ADC 动态范围', '接收链路灵敏度'],
  },
  loops: {
    title: 'Chirp 循环数 (Loops, Nd)',
    unit: '循环数 (loops/frame)',
    physicalMeaning: '在单帧 (Frame) 内部重复执行 Chirp 序列的次数。构成了多普勒速度 FFT 处理的核心维度。',
    ifIncreased: '延长多普勒观测总时长 Tobs = Loops × Ttx，精细化速度分辨率（Δv 变小），提升相干累积增益，但增加每帧数据量与发射时间。',
    ifDecreased: '减小单帧数据量与发射占空比，但多普勒 Bin 变宽，速度辨识能力下降。',
    relatedOutputs: ['速度分辨率 (Δv)', '多普勒观测窗口 (Tobs)', '帧有效发射时间', '每帧数据量'],
  },
  periodicityMs: {
    title: '帧周期 (Frame Periodicity)',
    unit: 'ms',
    physicalMeaning: '相邻两帧开始发射之间的总时间间隔。决定雷达帧率 (FPS = 1000 / 周期)。',
    ifIncreased: '降低帧率与占空比，降低芯片发热并减小以太网平均传输吞吐量。',
    ifDecreased: '提高雷达跟踪刷新率，但必须严格大于帧有效发射时间 (占空比 <= 100%)。',
    relatedOutputs: ['雷达帧率 (FPS)', '发射占空比 (%)', '平均以太网数据流速率 (MB/s)'],
  },
  frames: {
    title: '采集帧数 (Number of Frames)',
    unit: '帧 (frames)',
    physicalMeaning: '计划录制的总帧数。在 mmWave Studio 中设为 0 表示连续无限采集，直到手动发送停止指令。',
    ifIncreased: '延长实验连续录制时长，生成更大的原始二进制数据文件。',
    ifDecreased: '采集少量帧用于快速原型测试与验证。',
    relatedOutputs: ['总存储文件大小 (MB/GB)', '实验录制时长'],
  },
};

export const HelpTooltip: React.FC<{ paramKey: string; className?: string }> = ({
  paramKey,
  className = '',
}) => {
  const [open, setOpen] = useState(false);
  const { language } = useLanguage();
  const registry = language === 'zh' ? PARAMETER_HELP_ZH : PARAMETER_HELP_EN;
  const data = registry[paramKey] || PARAMETER_HELP_EN[paramKey];

  if (!data) return null;

  return (
    <span className={`inline-flex items-center relative ${className}`}>
      <button
        type="button"
        onClick={() => setOpen(!open)}
        className="ml-1 text-slate-400 hover:text-blue-600 focus:outline-none transition-colors"
        title={`Help for ${data.title}`}
        aria-label={`Help for ${data.title}`}
      >
        <HelpCircle className="w-3.5 h-3.5" />
      </button>

      {open && (
        <>
          <div
            className="fixed inset-0 z-40"
            onClick={() => setOpen(false)}
          />
          <div className="absolute left-6 top-0 z-50 w-80 max-w-sm bg-white border border-slate-300 rounded-lg shadow-xl p-3 text-xs text-slate-700 animate-in fade-in zoom-in-95">
            <div className="flex items-start justify-between border-b border-slate-200 pb-1.5 mb-2">
              <div>
                <span className="font-semibold text-slate-900">{data.title}</span>
                <span className="ml-2 font-mono text-[10px] bg-slate-100 text-slate-600 px-1.5 py-0.5 rounded">
                  {data.unit}
                </span>
              </div>
              <button
                type="button"
                onClick={() => setOpen(false)}
                className="text-slate-400 hover:text-slate-700"
              >
                <X className="w-3.5 h-3.5" />
              </button>
            </div>

            <p className="mb-2 text-slate-600 leading-relaxed">
              {data.physicalMeaning}
            </p>

            <div className="space-y-1.5 bg-slate-50 p-2 rounded border border-slate-200 mb-2">
              <div>
                <span className="font-medium text-emerald-700">
                  {language === 'zh' ? '▲ 增大该参数:' : '▲ If Increased:'}{' '}
                </span>
                <span className="text-slate-600">{data.ifIncreased}</span>
              </div>
              <div>
                <span className="font-medium text-amber-700">
                  {language === 'zh' ? '▼ 减小该参数:' : '▼ If Decreased:'}{' '}
                </span>
                <span className="text-slate-600">{data.ifDecreased}</span>
              </div>
            </div>

            <div className="text-[11px] text-slate-500">
              <span className="font-medium text-slate-700">
                {language === 'zh' ? '核心驱动输出: ' : 'Directly drives: '}
              </span>
              {data.relatedOutputs.join(', ')}
            </div>
          </div>
        </>
      )}
    </span>
  );
};
